# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 487b9c8051525f5367c15eade7bd8efc83ce89f1f406266d94a622e8470f21256e47c970a72f37419becdd5e876792bb7fa2f714886a02eca5bbc43f7ccdd9df

test:
  secret_key_base: 6b84dbaf9a15e10f45729c1bdb6fc1e89b6e3705eb6ac456e8fc9676ba66d4b597ca6d86c4084cb5b654c8b45584f4dd9ff0b3adb7c51023e1528797028732d0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
